import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li><Link href={"/products"}>Products</Link></li>
            <li><Link href={"/users"}>Users</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
